# Generated by Django 5.0.6 on 2024-05-14 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('featureflag', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('address', models.CharField(max_length=200)),
            ],
        ),
    ]
