name: Run Tests
on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest  # Install pytest
      # Set up Django settings module
      - name: Set up Django settings module
        run: |
         export DJANGO_SETTINGS_MODULE=githubaction.settings

      - name: Run Tests
        run: pytest featureflag/test.py
